name: "Semgrep SAST"

on:
  push:
    branches: [ "main", "master", "first_pipeline" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  semgrep-scan:
    name: Scan code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config "p/security-audit" --config "p/django" --config "p/owasp-top-ten" || true

          semgrep scan --config "p/security-audit" --config "p/django" --config "p/owasp-top-ten" --sarif -o semgrep-findings.sarif || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-report
          path: semgrep-findings.sarif
